apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    app.kubernetes.io/instance: your-argo-cd-application-name
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
      app.kubernetes.io/instance: your-argo-cd-application-name
  template:
    metadata:
      labels:
        app: guestbook-ui
        app.kubernetes.io/instance: your-argo-cd-application-name
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
